### ISSUE TITLE
Distinguish typography token names from heading tags

### ISSUE THREAD

**Issue by zetareticoli** [italia/design-tokens-italia#6]
### Does a discussion already exist on the topic you are interested in, or on a similar topic?

- [X] I verified and it doesn't exist

### What

Typography tokens: These are design system variables that define text styles, such as font size, weight, and line height. They are often named descriptively, like "heading-large" or "body-small".

Heading tags: These are HTML elements (h1, h2, h3, etc.) used to structure content hierarchically on a web page.

The distinction is important because while both relate to typography, they serve different purposes in the design and development process. 

### Why

Typography tokens are part of a design system, while heading tags are part of the HTML structure. 

Keeping them distinct helps maintain clarity in both design and code.

**Comment by Fupete** [comment]
Sarebbe la strada intrapresa da GOV.UK se capisco bene https://design-system.service.gov.uk/styles/type-scale/ in cui poi è spiegato come creare la scala tipografica del tuo template/mockup a livello di heading https://design-system.service.gov.uk/styles/headings/. 

Mi torna l'intento, segnalo però che ho la sensazione che questo potrebbe segnare un peggioramento, se ce ne fosse bisogno purtroppo, nel proliferare di gerarchie di heading non corrette (salti heading, stilati via classi css, h4 più piccoli di h3, etc. etc.) a livello di accessibilità già in fase di progettazione dei mock-up. Che poi nel passaggio a sviluppo potrebbero non essere indicate correttamente.
